name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    # FONTOS: Visszaállunk a régebbi, stabil Linuxra!
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2

      # Telepítjük a hiányzó eszközöket (libtool-bin, stb.)
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip \
            python3 python3-pip python3-dev \
            zlib1g-dev libffi-dev libssl-dev \
            autoconf automake libtool libtool-bin pkg-config \
            openjdk-11-jdk

      - name: Install Buildozer
        run: |
          pip3 install --user --upgrade Cython==0.29.33 buildozer virtualenv

      - name: Build APK
        run: |
          # FONTOS: Nincs "yes |" az elején!
          buildozer android debug
          
